intent = {
    "zh": {
        "wrong_token_name": "{}不是正确的代币名称或不在Solana链中",
        "wrong_chain_name": "链名错误，请提供正确的链名, 目前只支持Solana链",
        "wrong_contract": "合约地址错误，请提供正确的Solana合约地址",
        "wrong_wallet_name": "请提供正确的钱包名",
        "not_support_chain": "还不支持这条链,目前只支持用Solana做交易",
        "transaction": {
            "confirm": "请确认交易信息",
            "success_temp": "交易成功! 哈希值：",
            "success": "交易成功！用{} {} 交易获得 {} {}",
            "fail": "交易失败",
            "canceled": "交易取消",
            "do_not_have_token": "无法出售，您目前还没有该币",
            "do_not_have_sol": "无法购买，您还没有SOL,目前仅支持使用SOL来购买其他代币",
            "do_not_support_sell_token": "目前不支持出售SOL,您可以出售其他Solana链的代币",
            "do_not_support_buy_token": "目前不支持购买SOL,您可以购买其他Solana链的代币",
        },
        "wallet": {
            "create_success": "创建钱包成功！钱包名字是：{}, 地址是：{}",
            "create_fail": "创建钱包失败",
            "wrong_chain_name": "链名错误，请提供正确的链名,目前只支持Solana链",
            "wrong_token_name": "{}不是正确的代币名称或不在Solana链中",
            "import_success": "导入成功，钱包名字是：{}, 地址是{}",
            "import_fail": "导入失败",
            "wallet_list_success": "以下是您的钱包列表：",
            "wallet_list_fail": "查看钱包列表失败",
            "update_wallet_name_success": "改名成功！成功将钱包名 {} 改为 {}",
            "update_wallet_name_fail": "改名失败",
            "export_private_key_fail": "导出私钥失败",
            "export_private_key_success": "导出私钥成功，钱包名:{},私钥是:{}",
            "do_not_have_wallet": "您还没有钱包，您可以说「创建钱包」",
            "delete_fail": "钱包删除失败",
            "delete_success": "钱包删除成功,已删除名为{}的钱包",
        },
        "contract": {
            "contract_balance": "为您查到以下信息",
            "transaction_fail": "交易失败",
            "not_have_chain_wallet": "您还没有{}链的钱包，您可以说「创建一个{}链的钱包」",
            "search_token_chain": "为您查询到{}在{},但这条链我们还不支持，目前仅支持Solana链",
            "transaction_confirm": "请确认交易信息",
            "get_coin_info_fail": "获取代币信息发生错误，请稍后重试",
            "unknown_contract_address": "请提供正确的合约地址，目前支持查询钱包地址和Solana代币合约",
        },
        "subscript": {
            "wallet_address_success": "成功跟踪了该钱包地址。\n如果进行了任何链上交易，您将收到通知。\n您可以通过“监视-跟踪钱包”来管理您正在跟踪的钱包。",
            "wallet_address_fail": "跟踪钱包地址失败。",
            "twitter_success": "监控成功，已为您监控{}的推特，如果发布了推文，您将收到通知。",
            "twitter_fail": "监控推特失败",
            "news_success": "新闻订阅成功，\n如果有任何新闻消息，您将收到通知。",
            "news_cancel_success": "新闻取消订阅成功，\n您将不会收到任何新闻通知。",
            "news_fail": "新闻订阅失败，请稍后重试。",
            "exchange_success": "交易所公告订阅成功，{}有新的公告发布，您将收到通知。",
            "exchange_fail": "交易所公告订阅失败，请稍后重试。",
            "pool_success": "已成功监控了{}池子，您可以通过“监视-跟踪池子”来管理您监控的池子，可以设置池子范围。",
            "pool_fail": "监控池子失败，请稍后重试",
            "cancel_confirm": "以下是您的监控列表，您可以关闭不想监控的内容",
        },
        "subscript_list": {
            "exchange": {
                "okx": 10,
                "mexc": 56,
                "huobi": 99,
                "bitget": 111,
                "coinbase-exchange": 118,
                "kraken": 128,
                "gate.io": 156,
                "bithumb": 174,
                "kucoin": 176,
                "binance": 260,
                "upbit": 320,
            },
            "twitter": {
                "马斯克": "44196397",
                "V神": "295218901",
                "赵长鹏(CZ)": "902926941413453824",
                "币安官方": "877807935493033984",
                "Coinbase官方": "574032254",
                "孙宇晨": "1222182756400037889",
                "Jack(Xen创始人)": "207650884",
                "Coinbase国际": "1653212763693481985",
            },
            "trade": {},
            "news": {},
            "pool": {"SOL": "", "ETH": "", "BSC": "", "OP": "", "BASE": "", "ARB": ""},
        },
        "create_token": {"create_confirm": "乐意为您效劳，请告诉我你要发行的token信息，干一番大事业吧！"},
    },
    "en": {
        "wrong_token_name": "{} is not a valid token name or not on the Solana chain",
        "wrong_chain_name": "Chain name error. Please provide the correct chain name.The current version only supports Solana",
        "wrong_contract": "Contract address is incorrect. Please provide the correct Solana contract address.",
        "wrong_wallet_name": "Please provide the correct wallet name.",
        "not_support_chain": "The chain is not supported yet. The current version only supports Solana trading using Solana",
        "transaction": {
            "confirm": "Please confirm transaction details",
            "success_temp": "Transaction successful! ",
            "success": "Transaction successful! Swapped {} {} for {} {}",
            "fail": "Transaction failed",
            "canceled": "Transaction canceled",
            "do_not_have_token": "Unable to sell, you currently do not possess this token.",
            "do_not_have_sol": "Unable to purchase. You don't have any SOL. Currently, only SOL can be used to purchase other tokens.",
            "do_not_support_sell_token": "Currently, selling SOL is not supported. However, you can sell other tokens on the Solana network",
            "do_not_support_buy_token": "Currently, buying SOL is not supported. However, you can buy other tokens on the Solana network",
        },
        "wallet": {
            "create_success": "Wallet creation successful! The wallet name is:{}, address is: {}",
            "create_fail": "Wallet creation failed",
            "wrong_chain_name": "Chain name error. Please provide the correct chain name,The current version only supports Solana",
            "wrong_token_name": "{} is not a valid token name or not on the Solana chain",
            "import_success": "Import successful. The wallet name is:{}, address is {}",
            "import_fail": "Import failed",
            "wallet_list_success": "The following is your list of wallets:",
            "wallet_list_fail": "Checkout wallet list fail",
            "wrong_contract": "Contract is wrong,please provide a correct Solana contract",
            "update_wallet_name_success": "Name change successful! The wallet name has been successfully changed from {} to {}.",
            "update_wallet_name_fail": "Name change failed.",
            "export_private_key_fail": "Export private key failed",
            "export_private_key_success": "Private key export successful. Wallet name: {}, Private key is: {}",
            "do_not_have_wallet": "You don't have wallet,you can say「create wallet」",
            "delete_fail": "Delete wallet fail",
            "delete_success": "The wallet named {} has been deleted.",
        },
        "contract": {
            "contract_balance": "I have checked this for you.",
            "transaction_fail": "Make transaction fail",
            "not_have_chain_wallet": "You don't have a wallet for {} yet. You can say 「create a wallet for the {}」",
            "search_token_chain": "{} is found on the {}, but we do not support this chain yet, Currently we only support the Solana chain.",
            "transaction_confirm": "Please confirm the transaction details",
            "get_coin_info_fail": "An error occurred while retrieving token information. Please try again later.",
            "unknown_contract_address": "Please provide the correct contract address. Currently, we support querying wallet addresses and Solana token contracts.",
        },
        "subscript": {
            "wallet_address_success": "Successfully tracked this wallet.\nYou will be notified if any on-chain transactions are made. \nYou can manage the wallets you are tracking through Monitor-Track Wallet.",
            "wallet_address_fail": "Tracking wallet address failed.",
            "twitter_success": "Monitoring successful. We have monitored {}'s Twitter for you. You will receive notifications if any tweets are posted.",
            "twitter_fail": "Twitter monitoring failed.",
            "news_success": "News subscription successful. You will receive notifications for any news updates.",
            "news_cancel_success": "News unsubscribed successfully. You will not receive any news notifications.。",
            "news_fail": "News subscription failed. Please try again later.",
            "exchange_success": "The subscription to exchange announcements was successful. When there are new announcements from {}, you will receive notifications.",
            "exchange_fail": "The subscription to exchange announcements failed. Please try again later.",
            "pool_success": "The {} pool has been successfully monitored. You can manage your monitored pools through 'Monitor - Track Pools', where you can set the pool's scope.",
            "pool_fail": "Monitoring of the pool failed. Please try again later.",
            "cancel_confirm": "Here is your monitoring list, you can turn off the items you no longer wish to monitor.",
        },
        "subscript_list": {
            "exchange": {
                "okx": 10,
                "mexc": 56,
                "huobi": 99,
                "bitget": 111,
                "coinbase-exchange": 118,
                "kraken": 128,
                "gate.io": 156,
                "bithumb": 174,
                "kucoin": 176,
                "binance": 260,
                "upbit": 320,
            },
            "twitter": {
                "Elon Musk": "44196397",
                "Vitalik": "295218901",
                "CZ": "902926941413453824",
                "Binance": "877807935493033984",
                "Coinbase": "574032254",
                "Justin Sun": "1222182756400037889",
                "Jack(Founder of Xen)": "207650884",
                "Coinbase": "1653212763693481985",
            },
            "trade": {},
            "news": {},
            "pool": {},
        },
        "create_token": {
            "create_confirm": "Happy to serve you. Please provide me with the information about the token you intend to issue. Let's do something great!"
        },
    },
}
